
trigger:
  branches:
    include:
      - main

variables:
  # Azure Resource Manager Connection Name created in Azure DevOps Service Connections
  azureServiceConnection: 'my-azure-connection'
  resourceGroup: 'rg1'
  kubernetesCluster: 'myAKSCluster'
  # Docker Registry Connection Name created in Azure DevOps Service Connections
  dockerRegistryServiceConnection: 'my-docker-connection'
  imageRepository: 'projects'
  kustomizePath: 'Kubernetes/Chapter-4 Cloud/GitHub Actions-Pipeline'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.SourceVersion)

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # 1. Download source code repository in agent
    - checkout: self

    # 2. Install Kustomize CLI
    - task: KustomizeInstaller@1
      displayName: 'Install Kustomize'
      inputs:
        kustomizeVersion: 'latest'

    # 3. Update Image Tag using Kustomize
    - script: |
        cd "$(kustomizePath)"
        kustomize edit set image PROJECT/IMAGE=$(DOCKER_USERNAME)/$(imageRepository):$(Build.SourceVersion)
      displayName: 'Update Kustomize Image Tag'

    # 4. Render final manifests into a single output file
    - script: |
        kustomize build "$(kustomizePath)" > compiled-manifests.yaml
      displayName: 'Build Kustomize Manifests'

    # 5. Set Kubernetes Context and Deploy to AKS
    - task: KubernetesManifest@1
      displayName: 'Deploy to AKS'
      inputs:
        action: 'deploy'
        connectionType: 'Azure Resource Manager'
        azureSubscriptionConnection: '$(azureServiceConnection)'
        azureResourceGroup: '$(resourceGroup)'
        kubernetesCluster: '$(kubernetesCluster)'
        manifests: |
          compiled-manifests.yaml
